# Generated by Django 3.0.2 on 2020-09-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PunishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='VineyardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VineyardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('users', models.ManyToManyField(to='punishment_system.VineyardUser')),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments_given', to='punishment_system.VineyardUser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment_system.VineyardGroup')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to='punishment_system.VineyardUser')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment_system.PunishmentType')),
            ],
        ),
    ]
